package main.java.com.reponame.projname.controller;

import java.util.*;
import main.java.com.reponame.projname.service.RoleGroupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import javax.annotation.Resource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.servlet.http.HttpServletRequest;
@Controller@RequestMapping("/roleGroup")public class RoleGroupController {          @Resource    private RoleGroupService roleGroupService;        @Autowired      public RoleGroupController() {      }        @RequestMapping(value = "/", method = RequestMethod.GET)    public String home() {        return "index";      }            @RequestMapping(value = "/add", method = RequestMethod.POST)    public String addRoleGroup(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {          return "addRoleGroup";      }        @RequestMapping(value = "/addAll", method = RequestMethod.POST)    public String addAllRoleGroups(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {          return "addAllRoleGroups";      }        @RequestMapping(value = "/remove", method = RequestMethod.DELETE)    public String removeRoleGroupById(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {          return "removeRoleGroup";      }        @RequestMapping(value = "/removeAll", method = RequestMethod.DELETE)    public String removeAllRoleGroups(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {          return "removeAllRoleGroups";      }          @RequestMapping(value = "/modify", method = RequestMethod.PUT)    public String modifyRoleGroup(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {      	    	return "modifyRoleGroup";    }        @RequestMapping(value = "/modifyAll", method = RequestMethod.PUT)    public String modifyAllRoleGroups(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {      	    	return "modifyAllRoleGroups";    }              @RequestMapping(value = "/query", method = RequestMethod.GET)    public String queryRoleGroupById(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {      	    	return "queryRoleGroupById";    }        @RequestMapping(value = "/queryAll", method = RequestMethod.GET)    public String queryAllRoleGroups(HttpServletRequest request, @RequestParam Integer id, @RequestParam String roleGroupName, @RequestParam String modifiedBy, @RequestParam String createBy) {      	    	return "queryAllRoleGroups";    }}  