package main.java.com.reponame.projname.controller;

import java.util.*;
import main.java.com.reponame.projname.service.RoleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import javax.annotation.Resource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.servlet.http.HttpServletRequest;
@Controller@RequestMapping("/role")public class RoleController {          @Resource    private RoleService roleService;        @Autowired      public RoleController() {      }        @RequestMapping(value = "/", method = RequestMethod.GET)    public String home() {        return "index";      }            @RequestMapping(value = "/add", method = RequestMethod.POST)    public String addRole(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {          return "addRole";      }        @RequestMapping(value = "/addAll", method = RequestMethod.POST)    public String addAllRoles(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {          return "addAllRoles";      }        @RequestMapping(value = "/remove", method = RequestMethod.DELETE)    public String removeRoleById(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {          return "removeRole";      }        @RequestMapping(value = "/removeAll", method = RequestMethod.DELETE)    public String removeAllRoles(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {          return "removeAllRoles";      }          @RequestMapping(value = "/modify", method = RequestMethod.PUT)    public String modifyRole(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {      	    	return "modifyRole";    }        @RequestMapping(value = "/modifyAll", method = RequestMethod.PUT)    public String modifyAllRoles(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {      	    	return "modifyAllRoles";    }              @RequestMapping(value = "/query", method = RequestMethod.GET)    public String queryRoleById(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {      	    	return "queryRoleById";    }        @RequestMapping(value = "/queryAll", method = RequestMethod.GET)    public String queryAllRoles(HttpServletRequest request, @RequestParam Integer id, @RequestParam String modifiedBy, @RequestParam String roleName, @RequestParam Integer previligeLevel, @RequestParam String createBy) {      	    	return "queryAllRoles";    }}  